### PR TITLE
Update "Mac OS X" > "macOS"

### PR DESCRIPTION
**Pull request by lhaeger**
Just updating Apple's OS name on the splash screen and throughout comments.

### CODE REVIEW

**Comment by lhaeger** [comment]
Oops, should this rather go into "develop"?

**Comment by derreisende77** [comment]
OS X got named macOS string version 10.12. occurrences of 10.10 are still Mac OS X not macOS. 
Also I don‘t see a reason to replace Mac OS X with macOS  for the SystemUtil OS_NAME as AFAIK this comes straight from the JVM env. 

What is the reasoning/benefit of this PR?

And yes, all PRs should go to develop.

**Comment by lhaeger** [comment]
> OS X got named macOS starting version 10.12. occurrences of 10.10 are still Mac OS X not macOS.

Sierra was releases more than three years ago and according to OS version stats e.g. at https://www.adium.im/sparkle/#osVersion roughly 2/3 of all active installations are on 10.12 or higher already. Even on my 2013 MacBook I run Mojave and will soon update to Catalina.
"Mac OS X" simply looks outdated on the splash screen (unless someone hasn't updated their OS for years)

> Also I don‘t see a reason to replace Mac OS X with macOS for the SystemUtil OS_NAME as AFAIK this comes straight from the JVM env.

The Java environment needs to keep the old name for compatibility reasons, but SystemUtils.OS_NAME provides a keyword in a programming language, not necessarily an up-to-date user-facing display name.

> What is the reasoning/benefit of this PR?

Makes MV look modern and up-to-date rather than slightly outdated.

I was actually only after the splash screen text and hoped to catch that running sed recursively over the code. The comment changes are only collateral "damage" and not meant to offend.

> And yes, all PRs should go to develop.

Sorry for that, only discovered that after reading the bold red "Merging is blocked" message.

**Comment by derreisende77** [comment]
We have plenty of users running 10.10 (and even some running 10.6, 10.8) :( Minimum requirement for the Mac app is now Mac OS X 10.10. 
I will change the splash screen Text for macOS releases if there is an easy way to reliably detect the current version. Otherwise most of the comments predate the macOS era and are still valid for OS X so I wouldn’t change them. 
I will create an issue for the platform string.

**Comment by lhaeger** [comment]
Thanks a lot, _java.lang.System.getProperty("os.version")_ should do the trick, it's actually what _SystemUtils_ calls behind the scenes to initialize it's _OS_VERSION_ property, so that should report the same. 
On my machine I get:
`>System.getProperty("os.version")
10.14.6`

**Pull request closed without merging**
